### PR TITLE
Added bill related data services

### PR DESCRIPTION
**Pull request by TomRaz**

### CODE REVIEW

**Comment by OriHoch** [comment]
thanks @TomRaz ! 

Quick review of the code looks amazing!

but tests are failing.. I guess it's still a work in progress?

I prefixed the PR title with [WIP] = work in progress - so we will know not to merge it yet

**Comment by OriHoch** [comment]
I'm not sure how useful the tests are in this case, when it's just a mapping of api to schema

up to you, as far as I'm concerned, I'm happy to merge without tests so you can go on to the datapackage

when we have the zip with csv files it will also be easy to review and test the data

**Comment by TomRaz** [comment]
@OriHoch  - i agree about the tests, they are not really testing anything.
I added one file with integration tests that does a sanity check with each api, but added the "data_dependant_test" to it, so it won't run as part of the normal tests.

**Comment by OriHoch** [comment]
thanks @TomRaz let us know when it's ready for review/merge by removing the [WIP] prefix from title / and/or letting us know in a comment..

**Comment by TomRaz** [comment]
@OriHoch - PR is ready for review.
I cannot change the "Reviewers" in github for some reason, maybe i don't have the permissions?

**Pull request merged**
