### PR TITLE
[WIP] Python 3.6.1 compatibility

### PR DESCRIPTION
**Pull request by OriHoch**
started work on making code work for both Python 2.7 (which is used in Open Knesset) and Python 3.6.1 (which is required for datapackage-pipelines framework)

### CODE REVIEW

**Comment by alonisser** [comment]
Good idea. Compat should probably be 3.5 at least (if not before) starting from the shining brand new version is generally not a good idea for a lib, also if 3.6 then 3.6 and not 3.6.1 (since you are supposed to be supporting by major versions and not minor/patch versions)

**Comment by pwalsh** [comment]
@alonisser [Data Package Pipelines](https://github.com/frictionlessdata/datapackage-pipelines/blob/master/setup.py#L82) uses Python 3.6 features - can't support 3.5

**Comment by OriHoch** [comment]
I did some more work on this and now I'm thinking it might be easier to have datapackage pipelines support running python 2.7 processors (or more generally - language agnostic processors). 
But it's worth to upgrade anyway..

**Comment by OriHoch** [comment]
closing this PR, @gilwo will continue working on it

**Pull request closed without merging**
