### PR TITLE
Ticket#19 python 2 3

### PR DESCRIPTION
**Pull request by gilwo**
apply changes to allow knesset-data-python  to run in python2.7 and python3.6

### CODE REVIEW

**Comment by alonisser** [comment]
@gilwo A must when adding compatibility to a language version is adding it to travis-ci test matrix.

**Comment by alonisser** [comment]
@gilwo Also from the failing tests looks like you didn't add six (And maybe other libs?) to the requirements /setup.py

**Comment by gilwo** [comment]
@alonisser - i skipped some files from commit, i'll add those in the next batch of commits

**Comment by alonisser** [comment]
@gilwo I see you got the tests passing, but As far as I  can see you didn't add the supported python version to travis test grid, so passing tests could be verified for both supported language versions

**Comment by OriHoch** [comment]
related issue: #19

**Comment by gilwo** [comment]
i think this should cover things up

**Comment by gilwo** [comment]
i think this should cover things up

**Pull request merged**
